### ISSUE TITLE
Install with SPM

### ISSUE THREAD

**Issue by mohok** [candor/sublimate#14]
It can't be build if add url only.
`.package(url: "https://github.com/candor/sublimate.git", from: "1.0.0")`<- failed

I don't know how SPM works exactly. But I found another repo under same error.
https://github.com/apollographql/apollo-ios/issues/1102

I specified the package name and it works good now.
`.package(name: "Sublimate", url: "https://github.com/candor/sublimate", from: "1.10.0")`

**Comment by mxcl** [comment]
Works for us without `name:`.

**Comment by mohok** [comment]
I checked on my another mac. Still not working without `name:`. (Vapor 4.36.2, Swift 5.3.2)
Anyway, I'll close this issue. Thanks for your feedback!
